Disable tests on Windows
Error: failed to get `bat` as a dependency of package `git-delta v0.11.3 (D:\a\delta\delta)`
Caused by:
  failed to load source for dependency `bat`

Caused by:
  Unable to update https://github.com/dandavison/bat?rev=0b22913108152bda7fc1890616ebfabf02c8468a#0b229131

Caused by:
  failed to update submodule `assets/syntaxes/Jinja2`

Caused by:
  cannot checkout to invalid path 'Preferences/Symbol List: Blocks.tmPreferences'; class=Checkout (20)
Error: The process 'C:\Users\runneradmin\.cargo\bin\cargo.exe' failed with exit code 101